project:
  type: website

website:
  title: "Matt Triano"
  site-url: https://www.matttriano.dev
  description: "Experiments, walkthroughs past-me would have liked, and gifts to future me"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/MattTriano
      - icon: rss
        href: index.xml

listing:
  contents: posts
  feed: true

format:
  html:
    theme: darkly
    css: styles.css

execute:
  freeze: auto
