project:
  type: website

website:
  title: "Triano's Quarto Blog"
  site-url: https://www.matttriano.net
  description: "A blog by Matt Triano"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/MattTriano
      - icon: rss
        href: index.xml

format:
  html:
    theme: darkly
    css: styles.css

execute:
  freeze: auto
